version: '3'
services:
  front:
    networks:
      - default
    ports:
      - 46000:80
    build: 
      context: ./Front_DERES
      dockerfile: Dockerfile
    volumes:
      - .:/app
  
  register:
    networks:
      - default
    ports:
      - 46001:80
    build: 
      context: ./register
      dockerfile: Dockerfile
    volumes:
      - .:/app

networks:
  default:
    driver: bridge